name: Build Maven App on self-hosted VM.

on:
  push:
    branches: [ "develop" ]
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Maven compile
      run: mvn compile
    - name: Maven Test
      run: mvn test
    - name: Build with Maven
      run: mvn install
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target
    
